services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: quantix
      POSTGRES_USER: david
      POSTGRES_PASSWORD: admin456
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data   # ← corregido "postgreslq" → "postgresql"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: davyd2h@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    depends_on:
      - postgres

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: my_store
      MYSQL_USER: david
      MYSQL_PASSWORD: admin456
      MYSQL_ROOT_PASSWORD: admin456
    ports:
      - 33061:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: admin456
    ports:
      - 8080:80
    depends_on:
      - mysql